
CREATE TABLE IF NOT EXISTS `%TABLE_PREFIX%ckeditor_profiles` (
  `id` int(10) unsigned NOT NULL auto_increment,
  `name` varchar(50) NOT NULL DEFAULT '',
  `description` varchar(255) NOT NULL DEFAULT '',
  `jscode` text NOT NULL,
  `smartstrip` int(10) NOT NULL DEFAULT 1,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

INSERT IGNORE INTO `%TABLE_PREFIX%ckeditor_profiles` (`id`, `name`, `description`, `jscode`, `smartstrip`) VALUES
(1, 'lite', 'Einfache Konfiguration', '{\r\n    height: 400,\r\n    fillEmptyBlocks: false,\r\n    forcePasteAsPlainText: true,\r\n    entities: false,\r\n    linkShowTargetTab: false,\r\n    format_tags: ''p;h2;h3'',\r\n    removePlugins: ''elementspath'',\r\n    extraPlugins: ''rex_help'',\r\n    removeDialogTabs: ''link:advanced'',\r\n    disallowedContent: ''p{margin,margin-bottom,margin-left,margin-right,margin-top};img{border-style,border-width,margin,margin-bottom,margin-left,margin-right,margin-top};table{width,height}[align,border,cellpadding,cellspacing,summary];caption;'',\r\n    toolbar: [\r\n        [''Format''],\r\n        [''Bold'', ''Italic''],\r\n        [''NumberedList'', ''BulletedList'', ''-'', ''Outdent'', ''Indent''],\r\n        [''Link'', ''Unlink'', ''Anchor''],\r\n        [''Table''],\r\n        [''PasteText'', ''PasteFromWord''],\r\n        [''Maximize''],\r\n        [''rex_help'']\r\n        // no comma after last entry!!!\r\n    ]\r\n    // no comma after last entry!!!\r\n}', 1),
(2, 'standard', 'Standard Konfiguration', '{\r\n    height: 400,\r\n    fillEmptyBlocks: false,\r\n    forcePasteAsPlainText: false,\r\n    entities: false,\r\n    linkShowTargetTab: true,\r\n    format_tags: ''p;h1;h2;h3;pre'',\r\n    removePlugins: '''',\r\n    extraPlugins: ''rex_help'',\r\n    removeDialogTabs: '''',\r\n    disallowedContent: ''p{margin,margin-bottom,margin-left,margin-right,margin-top};img{border-style,border-width,margin,margin-bottom,margin-left,margin-right,margin-top};table{width,height}[align,border,cellpadding,cellspacing,summary];caption;'',\r\n    toolbar: [\r\n        [''Cut'', ''Copy'', ''Paste'', ''PasteText'', ''PasteFromWord'', ''-'', ''Undo'', ''Redo''],\r\n        [''Link'', ''Unlink'', ''Anchor''],\r\n        [''Image'', ''Table'', ''Seperator'', ''HorizontalRule'', ''SpecialChar''],\r\n        [''TextColor'', ''BGColor''],\r\n        [''CreateDiv''],\r\n        [''Maximize''],\r\n        [''Source''],\r\n        [''rex_help''],\r\n        ''/'',\r\n        [''Format'', ''Styles''],\r\n        [''Bold'', ''Italic'', ''Underline'', ''Strike'', ''Subscript'', ''Superscript'', ''-'', ''RemoveFormat''],\r\n        [''JustifyLeft'', ''JustifyCenter'', ''JustifyRight'', ''JustifyBlock''],\r\n        [''NumberedList'', ''BulletedList'', ''-'', ''Outdent'', ''Indent'', ''-'', ''Blockquote'']\r\n        // no comma after last entry!!!\r\n    ]\r\n    // no comma after last entry!!!\r\n}', 1),
(3, 'full', 'Vollständige Konfiguration', '{\r\n    height: 400,\r\n    fillEmptyBlocks: false,\r\n    forcePasteAsPlainText: false,\r\n    entities: false,\r\n    linkShowTargetTab: true,\r\n    format_tags: ''p;h1;h2;h3;pre'',\r\n    removePlugins: '''',\r\n    extraPlugins: ''rex_help'',\r\n    removeDialogTabs: '''',\r\n    disallowedContent: '''',\r\n    toolbar: [\r\n        [''Source'', ''-'', ''Save'', ''NewPage'', ''Preview'', ''Print'', ''-'', ''Templates''],\r\n        [''Cut'', ''Copy'', ''Paste'', ''PasteText'', ''PasteFromWord'', ''-'', ''Undo'', ''Redo''],\r\n        [''Find'', ''Replace'', ''-'', ''SelectAll'', ''-'', ''Scayt''],\r\n        [''Form'', ''Checkbox'', ''Radio'', ''TextField'', ''Textarea'', ''Select'', ''Button'', ''ImageButton'', ''HiddenField''],\r\n        ''/'',\r\n        [''Bold'', ''Italic'', ''Underline'', ''Strike'', ''Subscript'', ''Superscript'', ''-'', ''CopyFormatting'', ''RemoveFormat''],\r\n        [''NumberedList'', ''BulletedList'', ''-'', ''Outdent'', ''Indent'', ''-'', ''Blockquote'', ''CreateDiv'', ''-'', ''JustifyLeft'', ''JustifyCenter'', ''JustifyRight'', ''JustifyBlock'', ''-'', ''BidiLtr'', ''BidiRtl'', ''Language''],\r\n        [''Link'', ''Unlink'', ''Anchor''],\r\n        [''Image'', ''Flash'', ''Table'', ''HorizontalRule'', ''Smiley'', ''SpecialChar'', ''PageBreak'', ''Iframe''],\r\n        ''/'',\r\n        [''Styles'', ''Format'', ''Font'', ''FontSize''],\r\n        [''TextColor'', ''BGColor''],\r\n        [''Maximize'', ''ShowBlocks''],\r\n        [''rex_help'']\r\n        // no comma after last entry!!!\r\n    ]\r\n    // no comma after last entry!!!\r\n}', 1);
